Pallavi was shredding carrots at the dining room table. "Shut your mouth, woman," screamed Kumar uncle. His face betrayed a slight tremor while I hastily constructed a memory of spit flying and words cutting through the air in slow motion. "We were talking and you'd better mind your business." 

"Let's move to the hall," I suggested, noticing Michael's poker face contrasted with the sadness in Sariga's eyes. Uncle mumbled something as he drifted away, past Mathew's excitement and Peter's day dream. I filled my glass in the kitchen and apologised to Kumudh aunty. Spotting a packet of jujips on the fridge, I offered her one in an attempt to placate my guilt. She looked at me briefly and refused, politely, before looking back down at the bowl she was mixing. 

I chewed on one and offered the packet around the table. Had to skip Pramod, but I don't think he minded. Mathew asked for another one. "All gone," I said, opening my hand to show him the crumpled packet. The sugar that had fallen off the sweets shook themselves against the plastic. Uncle was in the background again, words unsaid traced across his face.

On the couch, Pramod kept his eyes on the tv while Kumar uncle spoke over him. "You see these tribals have no concept of ownership of land." "Like water and air," I assumed aloud. "So when the British came, it was easy to demarcate what was Government land. Now it's the government that sells the land to the large industries, all across Bihar, Orissa, Bengal." I wonder why I didn't suggest that industries imply employment.

We rattled past landfills on our way back from their house, where Pallavi had had a shower, and Pramod had picked up the large bowl and aunty's old iddiyappam maker. "They say you can bury all of earth's garbage in a big enough hole, and cover it with soil." Pramod nodded in agreement before opening his mouth as if to point out something. "Plastic is just like rock, when you think of it; the trees will grow." "Where would you find large holes," he quickly said. "All those old quarries, just fill them up with the garbage from these landfills, put enough soil on top and you have a nice forest."

Instead, I said "Just like the native Americans, haha." "And look where they are now, cornered into the smallest possible land." "Did you know about their casinos? People cross into the reservations to gamble, and the taxes aren't like Las Vegas. They make their money, but there's a culture of alcohol and violence and it isn't policed well either."
